# syntax=docker/dockerfile:1

# Multi-stage Dockerfile for building and running a Next.js blog in production

# You can adjust NODE_VERSION if needed. Next.js 15 supports Node 18+; we use Node 22 here.
ARG NODE_VERSION=25

############################
# Base stage: install deps #
############################
FROM node:${NODE_VERSION}-alpine AS deps

# Install system dependencies required by native modules (e.g., sharp)
RUN apk add --no-cache libc6-compat git

WORKDIR /app

# Copy lockfiles first for better caching; supports both npm and pnpm/yarn scenarios
# If you use pnpm or yarn, add their lockfiles here and adjust install commands accordingly.
COPY package.json package-lock.json* ./

# Install all dependencies (including dev) for building
# If you use a different package manager (pnpm/yarn), replace this with the appropriate command.
RUN npm ci

#############################
# Builder stage: build app  #
#############################
FROM node:${NODE_VERSION}-alpine AS builder

RUN apk add --no-cache libc6-compat git

WORKDIR /app

# Copy node_modules from deps stage
COPY --from=deps /app/node_modules ./node_modules
# Copy source
COPY . .

# Build the Next.js app
# Your package.json includes "prebuild" hook (tsx lib/scripts/preBuild.ts), so dev deps are required.
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

############################
# Runner stage: production #
############################
FROM node:${NODE_VERSION}-alpine AS runner

# Minimal runtime dependencies
RUN apk add --no-cache libc6-compat

WORKDIR /app

# Ensure Node runs in production mode and listen on all interfaces
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV HOSTNAME=0.0.0.0
ENV PORT=3000

# Copy Next.js standalone server and assets from builder
# The standalone output contains the production server, all necessary node_modules, and app code.
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

# Use a non-root user for better security
# Alpine image has a 'node' user by default
USER node

# Expose the Next.js port
EXPOSE 3000

# Start the server generated by Next.js standalone build
# The standalone output includes server.js at the project root we copied in.
CMD ["node", "server.js"]
